/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ldss.lojainformatica.view;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ldss.lojainformatica.DAO.ComputadorDAO;
import ldss.lojainformatica.model.Computador;

/**
 *
 * @author ldss1
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Computador objComputador;

    public TelaPrincipal() {
        initComponents();
        carregarTabela(ComputadorDAO.listarComputadores());;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void carregarTabela(ArrayList<Computador> listaComputadores) {

        DefaultTableModel modelo = (DefaultTableModel) tbl_Computadores.getModel();
        modelo.setNumRows(0);

        for (Computador computador : listaComputadores) {
            modelo.addRow(new String[]{
                String.valueOf(computador.getIdComputador()),
                String.valueOf(computador.getMarca()),
                String.valueOf(computador.getHd()),
                String.valueOf(computador.getProcessador())
            });
        }
    }

    private void editarComputador(int linhaSelecionada) {
        if (linhaSelecionada != -1) {
            objComputador = new Computador();
            objComputador.setMarca(tbl_Computadores.getValueAt(linhaSelecionada, 1).toString());
            objComputador.setHd(tbl_Computadores.getValueAt(linhaSelecionada, 2).toString());
            objComputador.setProcessador(tbl_Computadores.getValueAt(linhaSelecionada, 3).toString());
            objComputador.setIdComputador(Integer.parseInt(tbl_Computadores.getValueAt(linhaSelecionada, 0).toString()));

            TelaCadastro telaCadastro = new TelaCadastro(objComputador);
            telaCadastro.setVisible(true);
            telaCadastro.setAlwaysOnTop(rootPaneCheckingEnabled);
        } else {
            JOptionPane.showMessageDialog(this, "SELECIONE UMA LINHA", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Computadores = new javax.swing.JTable();
        btn_Adicionar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Apagar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmb_Processador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txt_Marca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Informatica");
        setAlwaysOnTop(true);

        tbl_Computadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MARCA", "HD", "PROCESSADOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Computadores);
        if (tbl_Computadores.getColumnModel().getColumnCount() > 0) {
            tbl_Computadores.getColumnModel().getColumn(0).setResizable(false);
            tbl_Computadores.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        btn_Adicionar.setText("ADICIONAR");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        btn_Editar.setText("EDITAR");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Apagar.setText("APAGAR");
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PESQUISAR"));

        cmb_Processador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "AMD", "APPLE SILICON", "INTEL", "QUALCOMM" }));
        cmb_Processador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProcessadorItemStateChanged(evt);
            }
        });

        jLabel1.setText("PROCESSADOR");

        txt_Marca.setText("Digite a marca do computador ...");
        txt_Marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_MarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MarcaFocusLost(evt);
            }
        });
        txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MarcaKeyTyped(evt);
            }
        });

        jLabel2.setText("MARCA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmb_Processador, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Processador, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_Marca)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btn_Apagar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        // TODO add your handling code here:
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);


    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbl_Computadores.getSelectedRow();
        editarComputador(linhaSelecionada);

    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbl_Computadores.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente apagar o computador selecionado?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {

                int idComputador = Integer.parseInt(tbl_Computadores.getValueAt(linhaSelecionada, 0).toString());
                boolean retorno = ComputadorDAO.apagarComputador(idComputador);
                if (retorno) {
                    JOptionPane.showMessageDialog(this, "Computador apagado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    carregarTabela(ComputadorDAO.listarComputadores());
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao apagar o computador!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um computador para apagar!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void cmb_ProcessadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProcessadorItemStateChanged
        // TODO add your handling code here:
        String processador = cmb_Processador.getSelectedItem().toString();
        if (processador.equals("TODOS")) {
            carregarTabela(ComputadorDAO.listarComputadores());
        } else {
            carregarTabela(ComputadorDAO.listarComputadoresPorProcessador(processador));
        }
    }//GEN-LAST:event_cmb_ProcessadorItemStateChanged

    private void txt_MarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MarcaKeyTyped
        // TODO add your handling code here:
        String marca = txt_Marca.getText();
        if (marca.equals("")) {
            carregarTabela(ComputadorDAO.listarComputadores());
        } else {
            carregarTabela(ComputadorDAO.listarComputadoresPorMarca(marca));
        }
    }//GEN-LAST:event_txt_MarcaKeyTyped

    private void txt_MarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MarcaFocusGained
        // TODO add your handling code here:
        if (txt_Marca.getText().equals("Digite a marca do computador ...")) {
            txt_Marca.setText("");
        }
    }//GEN-LAST:event_txt_MarcaFocusGained

    private void txt_MarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MarcaFocusLost
        // TODO add your handling code here:
        if (txt_Marca.getText().equals("")) {
            txt_Marca.setText("Digite a marca do computador ...");
        }
    }//GEN-LAST:event_txt_MarcaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Apagar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JComboBox<String> cmb_Processador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tbl_Computadores;
    private javax.swing.JTextField txt_Marca;
    // End of variables declaration//GEN-END:variables
}
