CREATE DATABASE Clinica;

USE Clinica;

CREATE TABLE Ambulatorios(
	NROA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Andar INT NOT NULL,
	Capacidade SMALLINT
);

CREATE TABLE Medicos(
	CODM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(40) NOT NULL,
	Idade SMALLINT NOT NULL,
	Especialidade CHAR(20),
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Cidade VARCHAR(30),
	fk_NROA INT,
	FOREIGN KEY(fk_NROA) REFERENCES Ambulatorios(NROA)
);

CREATE TABLE Pacientes(
	CODP INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(40) NOT NULL,
	Idade SMALLINT NOT NULL,
	Cidade VARCHAR(30),
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Doenca VARCHAR(40) NOT NULL
);

CREATE TABLE Funcionarios(
	CODF INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(40) NOT NULL,
	Idade SMALLINT,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Cidade VARCHAR(30),
	Salario NUMERIC(10,2),
	Cargo VARCHAR(20)
);

CREATE TABLE Consultas(
	CODC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Data_Consulta DATE,
	Hora_Consulta TIME,
	fk_CODM INT,
	fk_CODP INT,
	FOREIGN KEY(fk_CODM) REFERENCES Medicos(CODM),
	FOREIGN KEY(fk_CODP) REFERENCES Pacientes(CODP)
);

-- Crie COLUNA
ALTER TABLE Funcionarios ADD COLUMN fk_NROA INT;

-- Crie CONSTRAINT
ALTER TABLE Funcionarios ADD CONSTRAINT fk_NROA FOREIGN KEY(fk_NROA) REFERENCES Ambulatorios(NROA);

-- Remove Coluna
ALTER TABLE Funcionarios DROP COLUMN Cargo;

-- O paciente Paulo mudou-se para Ilhota


